INSERT IGNORE INTO quotes (quote) VALUES ('"Where there is tea there is hope"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Navis bellica Russica te ipsam pedica!"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Rationalism is not the only thing that drives human action. We are foolish creatures - Tanya von Degurechaff"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Victory. Such a tempting thing. Naturally everyone wants to savor a taste - Tanya von Degurechaff"');
INSERT IGNORE INTO quotes (quote) VALUES ('"No matter how much we modernize no matter how social norms affect us humans are foolish creatures - Tanya von Degurechaff"');
INSERT IGNORE INTO quotes (quote) VALUES ('"They say a thin line separates genius and madness - Tanya von Degurechaff"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Res ad triaros venit"');
INSERT IGNORE INTO quotes (quote) VALUES ('"It is I Leclerc!"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Listen very carefully I shall say this only once"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Alea iacta est"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Są dwa racjonalne wytłumaczenia - jeden fizyka czarnej dziury - dwa czary"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Austria est imperare orbi universo"');
INSERT IGNORE INTO quotes (quote) VALUES ('"My only friends have always just been tanks"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Armia rosyjska jest niezwycięzona - bo nie zwycięża"');
INSERT IGNORE INTO quotes (quote) VALUES ('"We want - A shrubbery!"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Ani kroku dalej onuco bo ta wyrzutnia zaśpiewa hej sokoły"');
INSERT IGNORE INTO quotes (quote) VALUES ('"There is nothing that deserves more of my attention than goblins"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Pro gloria Roma"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Hello there"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Widok pędzącego brytyjskiego czołgu zawsze wywołuje uśmiech na mej twarzy!"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Potężna wichura łamiąc duże drzewa trzciną zaledwie kołysze"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Come non funziona?"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Come now and walk the path of explosions with me!"');
INSERT IGNORE INTO quotes (quote) VALUES ('"And Rohan will answer"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Gapisz mi się na bebech?"');
INSERT IGNORE INTO quotes (quote) VALUES ('"You know Jim or Jim knows you?"');
INSERT IGNORE INTO quotes (quote) VALUES ('"A shovel is an implement born of civilization. Hooray for civilization - Tanya von Degurechaff"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Shovels are great. Shovels are the quintessence of civilization"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Et tu Brute contra me?"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Frankly I enjoyed the war"');
INSERT IGNORE INTO quotes (quote) VALUES ('"Je crois en moi"');
INSERT IGNORE INTO quotes (quote) VALUES ('""');
